version: '3.9'

services:
  web: 
    command: python3 app.py
    image: st124856/car_price_3:v1.9
    environment:
      - HOST=0.0.0.0
      - PORT=80
    labels:
      # Allow Traefik to talk with yout service
      - traefik.enable=true
      # Tell Traefil to use port 80
      - traefik.http.services.web-st124856_a3.loadbalancer.server.port=80
      #This config you domain name. By Default, your subdomain name is web-st124856_a3
      # If you want to change your subdomain name, you uncomment the below configuration
      - traefik.http.routers.web-st124856_a3.rule=Host(`st124856_a3.ml.brain.cs.ait.ac.th`)
      # Below is for enable SSL
      - traefik.http.routers.web-st124856_a3.tls=true
      - traefik.http.routers.web-st124856_a3.tls.certresolver=production
      - traefik.http.routers.web-st124856_a3.entrypoints=websecure

    networks:
      - default
      - traefik_default
  

networks:
  default:
  traefik_default:
    external: true