version: "3.9"

services:
  car-price-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: car_price_app
    volumes:
      - ./code:/app  # Mount the code directory for development
    ports:
      - "6000:6000"  # Map container port 6000 to host port 6000
    stdin_open: true  # Keep container open for interactive debugging
    tty: true         # Allocate a pseudo-TTY
